var element = document.getElementById("id01");element.innerHTML = "ACTIVE CASE- 	325	&nbsp;&nbsp;			&nbsp;&nbsp;RECOVERD -	14					";					
																
																
																
																
																
var myApp = angular.module('myApp', ['ngRoute'])																
																
//ng-route config																
.config(function ($routeProvider, $locationProvider){																
  $routeProvider																
    .when('/home', {																
      templateUrl: 'default.html',																
    })																
    .when('/contact-info/:contact_index', {																
      templateUrl: 'contact_info.html',																
      controller: 'contactInfoCtrl'																
    })																
    																
    .otherwise({redirectTo: '/home'});																
})																
																
// controllers																
.controller('navCtrl', function ($scope) {																
  $scope.nav = {																
    navItems: ['home', 'add'],																
    selectedIndex: 0,																
    navClick: function ($index) {																
      $scope.nav.selectedIndex = $index;																
    }																
  };																
})																
																
.controller('homeCtrl', function ($scope, ContactService){																
  $scope.contacts = ContactService.getContacts();																
})																
																
.controller('contactInfoCtrl', function ($scope, $routeParams){																
  var index = $routeParams.contact_index;																
  $scope.currentContact = $scope.contacts[index];																
})																
																
																
																
// directives																
.directive('contact', function () {																
  return {																
    restrict: 'E',																
    replace: true,																
    templateUrl: 'contact.html'																
  }																
})																
																
// services																
.factory('ContactService', [function () {																
  var factory = {};																
																
  factory.getContacts = function () {																
    return contactList;																
  }																
																
  // contact list, usually would be a separate database																
  var contactList = [																
																
{id: 1, name: '	28-11-21', total: '  ', 													
customer1: '	DURG	', toys1: 'POSITIVE:-	', amount1: 'RECOVERED-	7	',  url1: '	5	', GIFTS1: 'DEATH:-	0	', amountg1: 'ACTIVE-	54	', bags1: 'BAGS:-	', amountb1: '		',  urlb1: '		',
customer2: '	RAJNANDGAON	', toys2: 'POSITIVE:-	', amount2: 'RECOVERED-	0	',  url2: '	0	', GIFTS2: 'DEATH:-	0	', amountg2: ' ACTIVE-	12	', bags2: 'BAGS:-	', amountb2: '		',  urlb2: '		',
customer3: '	BALOD	', toys3: 'POSITIVE:-	', amount3: 'RECOVERED-	1	',  url3: '	1	', GIFTS3: 'DEATH:-	0	', amountg3: ' ACTIVE-	4	', bags3: 'BAGS:-	', amountb3: '		',  urlb3: '		',
customer4: '	BEMETARA	', toys4: 'POSITIVE:-	', amount4: 'RECOVERED-	0	',  url4: '	0	', GIFTS4: 'DEATH:-	0	', amountg4: 'ACTIVE-	3	', bags4: 'BAGS:-	', amountb4: '		',  urlb4: '		',
customer5: '	KABIRDHAM	', toys5: 'POSITIVE:-	', amount5: 'RECOVERED-	0	',  url5: '	0	', GIFTS5: 'DEATH:-	0	', amountg5: 'ACTIVE-	1	', bags5: 'BAGS:-	', amountb5: '		',  urlb5: '		',
customer6: '	RAIPUR	', toys6: 'POSITIVE:-	', amount6: 'RECOVERED-	7	',  url6: '	5	', GIFTS6: 'DEATH:-	0	', amountg6: 'ACTIVE-	54	', bags6: 'BAGS:-	', amountb6: '		',  urlb6: '		',
customer7: '	DHAMTARI	', toys7: 'POSTIVE:-	', amount7: 'RECOVERED-	2	',  url7: '	2	', GIFTS7: 'DEATH:-	0	', amountg7: 'ACTIVE-	18	', bags7: 'BAGS:-	', amountb7: '		',  urlb7: '		',
customer8: '	BALODABAZAR	', toys8: 'POSITIVE:-	', amount8: 'RECOVERED-	1	',  url8: '	0	', GIFTS8: 'DEATH:-	0	', amountg8: 'ACTIVE-	4	', bags8: 'BAGS:-	', amountb8: '		',  urlb8: '		',
customer9: '	MAHASAMUH	', toys9: 'POSITIVE:-	', amount9: 'RECOVERED-	1	',  url9: '	1	', GIFTS9: 'DEATH:-	0	', amountg9: 'ACTIVE-	6	', bags9: 'BAGS:-	', amountb9: '		',  urlb9: '		',
customer10: '	GARIYABAND	', toys10: 'POSITIVE:-	', amount10: 'RECOVERED-	6	',  url10: '	0	', GIFTS10: 'DEATH:-	0	', amountg10: 'ACTIVE-	7	', bags10: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer11: '	BILASPUR	', toys11: 'POSITIVE:-	', amount11: 'RECOVERED-	2	',  url11: '	3	', GIFTS11: 'DEATH:-	0	', amountg11: 'ACTIVE-	11	', bags11: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer12: '	RAIGARH	', toys12: 'POSITIVE:-	', amount12: 'RECOVERED-	3	',  url12: '	0	', GIFTS12: 'DEATH:-	0	', amountg12: 'ACTIVE-	52	', bags12: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer13: '	KORBA	', toys13: 'POSITIVE:-	', amount13: 'RECOVERED-	3	',  url13: '	0	', GIFTS13: 'DEATH:-	0	', amountg13: 'ACTIVE-	20	', bags13: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer14: '	JANJGIR CHAMPA	', toys14: 'POSITIVE:-	', amount14: 'RECOVERED-	1	',  url14: '	1	', GIFTS14: 'DEATH:-	0	', amountg14: 'ACTIVE-	9	', bags14: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer15: '	MUNGELI	', toys15: 'POSITIVE:-	', amount15: 'RECOVERED-	0	',  url15: '	0	', GIFTS15: 'DEATH:-	0	', amountg15: 'ACTIVE-	3	', bags15: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer16: '	PENDRA	', toys16: 'POSITIVE:-	', amount16: 'RECOVERED-	0	',  url16: '	0	', GIFTS16: 'DEATH:-	0	', amountg16: 'ACTIVE-	0	', bags16: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer17: '	SARGUJA	', toys17: 'POSITIVE:-	', amount17: 'RECOVERED-	0	',  url17: '	2	', GIFTS17: 'DEATH:-	0	', amountg17: 'ACTIVE-	8	', bags17: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer18: '	KOREA	', toys18: 'POSITIVE:-	', amount18: 'RECOVERED-	0	',  url18: '	0	', GIFTS18: 'DEATH:-	0	', amountg18: 'ACTIVE-	2	', bags18: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer19: '	SURAJPUR	', toys19: 'POSITIVE:-	', amount19: 'RECOVERED-	0	',  url19: '	1	', GIFTS19: 'DEATH:-	0	', amountg19: 'ACTIVE-	1	', bags19: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer20: '	BALRAMPUR	', toys20: 'POSITIVE:-	', amount20: 'RECOVERED-	0	',  url20: '	0	', GIFTS20: 'DEATH:-	0	', amountg20: 'ACTIVE-	0	', bags20: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer21: '	JASHPUR	', toys21: 'POSITIVE:-	', amount21: 'RECOVERED-	0	',  url21: '	0	', GIFTS21: 'DEATH:-	0	', amountg21: 'ACTIVE-	25	', bags21: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer22: '	BASTAR	', toys22: 'POSITIVE:-	', amount22: 'RECOVERED-	0	',  url22: '	0	', GIFTS22: 'DEATH:-	0	', amount22: 'ACTIVE-	9	', bags22: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer23: '	KONDAGAON	', toys23: 'POSITIVE:-	', amount23: 'RECOVERED-	0	',  url23: '	0	', GIFTS23: 'DEATH:-	0	', amountg23: 'ACTIVE-	1	', bags23: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer24: '	DANTEWADA	', toys24: 'POSITIVE:-	', amount24: 'RECOVERED-	1	',  url24: '	2	', GIFTS24: 'DEATH:-	0	', amountg24: 'ACTIVE-	18	', bags24: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer25: '	SUKTA	', toys25: 'POSITIVE:-	', amount25: 'RECOVERED-	0	',  url25: '	0	', GIFTS25: 'DEATH:-	0	', amountg25: 'ACTIVE-	0	', bags25: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer26: '	KANKER	', toys26: 'POSITIVE:-	', amount26: 'RECOVERED-	1	',  url26: '	0	', GIFTS26: 'DEATH:-	0	', amountg26: 'ACTIVE-	2	', bags26: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer27: '	NARAYANPUR	', toys27: 'POSITIVE:-	', amount27: 'RECOVERED-	0	',  url27: '	0	', GIFTS27: 'DEATH:-	0	', amountg27: 'ACTIVE-	0	', bags27: 'BAGS:-	', amountb10: '		',  urlb10: '		',
customer28: '	BIJAPUR	', toys28: 'POSITIVE:-	', amount28: 'RECOVERED-	0	',  url28: '	0	', GIFTS28: 'DEATH:-	0	', amountg28: 'ACTIVE-	1	', bags28: 'BAGS:-	', amountb10: '		',  urlb10: '		',
																
	},
															
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
  ];																
  																
  return factory;																
}]);																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
																
