var numOne = document.getElementById("num-one");
var numOne1 = document.getElementById("num-one1");
var numOne2 = document.getElementById("num-one2");
var numOne3 = document.getElementById("num-one3");
var numOne4 = document.getElementById("num-one4");
var numOne5 = document.getElementById("num-one5");
var numOne6 = document.getElementById("num-one6");
var numOne7 = document.getElementById("num-one7");
var numOne8 = document.getElementById("num-one8");
var numOne9 = document.getElementById("num-one9");
var numOne10 = document.getElementById("num-one10");
var numOne11 = document.getElementById("num-one11");
var numOne12 = document.getElementById("num-one12");
var numOne13 = document.getElementById("num-one13");
var numOne14 = document.getElementById("num-one14");
var numOne15 = document.getElementById("num-one15");
var numOne16 = document.getElementById("num-one16");
var numOne17 = document.getElementById("num-one17");
var numOne18 = document.getElementById("num-one18");
var numOne19 = document.getElementById("num-one19");
var numOne20 = document.getElementById("num-one20");
var numOne100 = document.getElementById("num-one100");
var addSum = document. getElementById("add-sum");
var addSum1 = document. getElementById("add-sum1");
var addSum2 = document. getElementById("add-sum2");
var addSum3 = document. getElementById("add-sum3");
var addSum4 = document. getElementById("add-sum4");
var addSum5 = document. getElementById("add-sum5");
var addSum6 = document. getElementById("add-sum6");
var addSum7 = document. getElementById("add-sum7");
var addSum8 = document. getElementById("add-sum8");
var addSum9 = document. getElementById("add-sum9");
var addSum10 = document. getElementById("add-sum10");
var addSum11 = document. getElementById("add-sum11");
var addSum12 = document. getElementById("add-sum12");
var addSum13 = document. getElementById("add-sum13");
var addSum14 = document. getElementById("add-sum14");
var addSum15 = document. getElementById("add-sum15");
var addSum16 = document. getElementById("add-sum16");
var addSum17 = document. getElementById("add-sum17");
var addSum18 = document. getElementById("add-sum18");
var addSum19 = document. getElementById("add-sum19");
var addSum20 = document. getElementById("add-sum20");
var addSum100 = document. getElementById("add-sum100");
var addSumtotal = document. getElementById("add-sumtotal");

numOne.addEventListener("input", add);
numOne1.addEventListener("input", add);
numOne2.addEventListener("input", add);
numOne3.addEventListener("input", add);
numOne4.addEventListener("input", add);
numOne5.addEventListener("input", add);
numOne6.addEventListener("input", add);
numOne7.addEventListener("input", add);
numOne8.addEventListener("input", add);
numOne9.addEventListener("input", add);
numOne10.addEventListener("input", add);
numOne11.addEventListener("input", add);
numOne12.addEventListener("input", add);
numOne13.addEventListener("input", add);
numOne14.addEventListener("input", add);
numOne15.addEventListener("input", add);
numOne16.addEventListener("input", add);
numOne17.addEventListener("input", add);
numOne18.addEventListener("input", add);
numOne19.addEventListener("input", add);
numOne20.addEventListener("input", add);
numOne100.addEventListener("input", add);

function add(){
  var one = Number(numOne.value) || 0;
  var one1 = Number(numOne1.value) || 0;
  var one2 = Number(numOne2.value) || 0;
  var one3 = Number(numOne3.value) || 0;
  var one4 = Number(numOne4.value) || 0;
  var one5 = Number(numOne5.value) || 0;
  var one6 = Number(numOne6.value) || 0;
  var one7 = Number(numOne7.value) || 0;
  var one8 = Number(numOne8.value) || 0;
  var one9 = Number(numOne9.value) || 0;
  var one10 = Number(numOne10.value) || 0;
  var one11 = Number(numOne11.value) || 0;
  var one12 = Number(numOne12.value) || 0;
  var one13 = Number(numOne13.value) || 0;
  var one14 = Number(numOne14.value) || 0;
  var one15 = Number(numOne15.value) || 0;
  var one16 = Number(numOne16.value) || 0;
  var one17 = Number(numOne17.value) || 0;
  var one18 = Number(numOne18.value) || 0;
  var one19 = Number(numOne19.value) || 0;
  var one20 = Number(numOne20.value) || 0;
  var one100 = Number(numOne100.value) || 0;
  var sum = Number(one*0.60);
  var sum1 = Number(one1*0.60);
  var sum2 = Number(one2*0.60);
  var sum3 = Number(one3*0.60);
  var sum4 = Number(one4*0.60);
  var sum5 = Number(one5*0.60);
  var sum6 = Number(one6*0.60);
  var sum7 = Number(one7*0.60);
  var sum8 = Number(one8*0.60);
  var sum9 = Number(one9*0.60);
  var sum10 = Number(one10*0.60);
  var sum11 = Number(one11*0.60);
  var sum12 = Number(one12*0.60);
  var sum13 = Number(one13*0.60);
  var sum14 = Number(one14*0.60);
  var sum15 = Number(one15*0.60);
  var sum16 = Number(one16*0.60);
  var sum17 = Number(one17*0.60);
  var sum18 = Number(one18*0.60);
  var sum19 = Number(one19*0.60);
  var sum20 = Number(one20*0.60);
  var sum100 = Number(one100);
  var sumtotal = Number(sum100+sum+sum1+sum2+sum3+sum4+sum5+sum6+sum7+sum8+sum9+sum10+sum11+sum12+sum13+sum14+sum15+sum16+sum17+sum18+sum19+sum20);
  addSum.innerHTML = "PRICE: " + sum + " Rs. ";
  addSum1.innerHTML = "PRICE: " + sum1 + " Rs. ";
  addSum2.innerHTML = "PRICE: " + sum2 + " Rs. ";
  addSum3.innerHTML = "PRICE: " + sum3 + " Rs. ";
  addSum4.innerHTML = "PRICE: " + sum4 + " Rs. ";
  addSum5.innerHTML = "PRICE: " + sum5 + " Rs. ";
  addSum6.innerHTML = "PRICE: " + sum6 + " Rs. ";
  addSum7.innerHTML = "PRICE: " + sum7 + " Rs. ";
  addSum8.innerHTML = "PRICE: " + sum8 + " Rs. ";
  addSum9.innerHTML = "PRICE: " + sum9 + " Rs. ";
  addSum10.innerHTML = "PRICE: " + sum10 + " Rs. ";
  addSum11.innerHTML = "PRICE: " + sum11 + " Rs. ";
  addSum12.innerHTML = "PRICE: " + sum12 + " Rs. ";
  addSum13.innerHTML = "PRICE: " + sum13 + " Rs. ";
  addSum14.innerHTML = "PRICE: " + sum14 + " Rs. ";
  addSum15.innerHTML = "PRICE: " + sum15 + " Rs. ";
  addSum16.innerHTML = "PRICE: " + sum16 + " Rs. ";
  addSum17.innerHTML = "PRICE: " + sum17 + " Rs. ";
  addSum18.innerHTML = "PRICE: " + sum18 + " Rs. ";
  addSum19.innerHTML = "PRICE: " + sum19 + " Rs. ";
  addSum20.innerHTML = "PRICE: " + sum20 + " Rs. ";
  addSum100.innerHTML = "PRICE: " + sum100 + " Rs. ";
  addSumtotal.innerHTML = "total: " + sumtotal + " Rs. ";
}